name: Shell comands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a string
        run: echo "Hello Git Actions World!!"

      - name: multiline script
        run: |
          echo ">> Inicio do STEP: Multiline Script"
          echo ">> Verificando versão do NODE"
          node -v 
          echo ">> Verificando a versão do NPM"
          npm -v
          echo ">> Verificando a versão do PYTHON"
          python -V
          echo ">> Fim do STEP: Multiline Script"
